/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.interactiva;

import proyecto.interactiva.GestionUsuario.vista.*;
import proyecto.interactiva.GestionUsuario.controlador.ControlUsuario;

/**
 *
 * @author Frank E. Gil M.
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ControlUsuario cu;
    public Principal() {
        initComponents();
        cu = new ControlUsuario();
        cu.listadoTipo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        MenuBar_Inicio = new javax.swing.JMenu();
        MenuItem_login = new javax.swing.JMenuItem();
        MenuItem_Registrar = new javax.swing.JMenuItem();
        MenuItem_CerrarSesion = new javax.swing.JMenuItem();
        MenuBar_Usuarios = new javax.swing.JMenu();
        jMenuItem_Listado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario en Sesión:");

        lblUsuario.setToolTipText("");

        MenuBar_Inicio.setText("Inicio");

        MenuItem_login.setText("Iniciar Sesión");
        MenuItem_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_loginActionPerformed(evt);
            }
        });
        MenuBar_Inicio.add(MenuItem_login);

        MenuItem_Registrar.setText("Registrar");
        MenuItem_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_RegistrarActionPerformed(evt);
            }
        });
        MenuBar_Inicio.add(MenuItem_Registrar);

        MenuItem_CerrarSesion.setText("Cerrar Sesión");
        MenuItem_CerrarSesion.setEnabled(false);
        MenuItem_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_CerrarSesionActionPerformed(evt);
            }
        });
        MenuBar_Inicio.add(MenuItem_CerrarSesion);

        menuBarra.add(MenuBar_Inicio);

        MenuBar_Usuarios.setText("Usuarios");
        MenuBar_Usuarios.setEnabled(false);

        jMenuItem_Listado.setText("Listado");
        jMenuItem_Listado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ListadoActionPerformed(evt);
            }
        });
        MenuBar_Usuarios.add(jMenuItem_Listado);

        menuBarra.add(MenuBar_Usuarios);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_ListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ListadoActionPerformed
        listado();
    }//GEN-LAST:event_jMenuItem_ListadoActionPerformed

    private void MenuItem_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_loginActionPerformed
        // TODO add your handling code here:
        Login_Usuario login = new Login_Usuario(this);
        login.setLocationRelativeTo(this);
        login.setVisible(true);
    }//GEN-LAST:event_MenuItem_loginActionPerformed

    private void MenuItem_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_RegistrarActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.updateUI();
        Registro_Usuario registro = new Registro_Usuario();
        registro.setSize(400, 300);
        System.out.println(cu.isBandera());
        registro.cbxUsuarios.setEnabled(cu.isBandera());
        Contenedor.add(registro);
        registro.setVisible(true);
        Contenedor.validate();
    }//GEN-LAST:event_MenuItem_RegistrarActionPerformed

    private void MenuItem_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_CerrarSesionActionPerformed
        // TODO add your handling code here:
        Contenedor.removeAll();
        Contenedor.updateUI();
        MenuBar_Usuarios.setEnabled(false);
        MenuItem_CerrarSesion.setEnabled(false);
        ControlUsuario.usuario_sesion = null;
        lblUsuario.setText("");
    }//GEN-LAST:event_MenuItem_CerrarSesionActionPerformed

    public void listado() {
        Contenedor.removeAll();
        Contenedor.updateUI();
        Listado lista = new Listado();
        lista.setSize(700, 410);
        Contenedor.add(lista);
        lista.setVisible(true);
        Contenedor.validate();
    }

    public void habilitar(String nombre) {
        for (int i = 0; i < menuBarra.getMenuCount(); i++) {
            if (menuBarra.getMenu(i).getActionCommand().equals(nombre)) {
                menuBarra.getMenu(i).setEnabled(true);
            }else if (MenuItem_CerrarSesion.getActionCommand().equals(nombre)){
                MenuItem_CerrarSesion.setEnabled(true);
            }
        }
    }
    public void mostrarUsuario() {
        lblUsuario.setText(ControlUsuario.usuario_sesion.getNombre());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JMenu MenuBar_Inicio;
    private javax.swing.JMenu MenuBar_Usuarios;
    private javax.swing.JMenuItem MenuItem_CerrarSesion;
    private javax.swing.JMenuItem MenuItem_Registrar;
    private javax.swing.JMenuItem MenuItem_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem_Listado;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar menuBarra;
    // End of variables declaration//GEN-END:variables
}
